### ISSUE TITLE
Error on 4/30 update.

### ISSUE THREAD

**Issue by b-b-wagner** [metxchris/TT2-Sim#1]
Successfuly using pre 4/30 version.  As of most recent update, get following error when run with default Swordmaster.csv.

Traceback (most recent call last):
  File "C:\Users\XXX\Downloads\TT2-Sim-master\TT2-Simulation.py", line 1035, in <module>
    player, stage = run_simulation('SwordMaster.csv')
  File "C:\Users\XXX\Downloads\TT2-Sim-master\TT2-Simulation.py", line 1015, in run_simulation
    data = GameData(input_csv)
  File "core\DataClasses.py", line 25, in __init__
    self.input = np.genfromtxt(dir_path()+'player\\'+input_file, delimiter=',', dtype=str)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 1453, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rb'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\_datasource.py", line 499, in open
    return _file_openers[ext](found, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '..\\player\\SwordMaster.csv'
[Finished in 1.8s]

**Comment by Marzx13** [comment]
I have the same issue. i am pretty sure it is because one of the servicer based CSV's uses '\' inseat of ',' you can replace all instances of the \\ with a \ on the 'DataClasses.py' file. I personally have not getten it working yet.

**Comment by metxchris** [comment]
I'll roll this back tomorrow, thanks for the heads up.  

Edit: It should be fixed now.
